# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b52f06fda334bc1c0a0b2f494fad1d034ce6f89dbfccac7496d11fbf2f6233ab7284c099d9e10a3560ced35156f7e2679f04d2d97be0c84b301d084c1418cb4

test:
  secret_key_base: b145da2061a7a0f9935b05c3af5dd14a5b17b746b4c246132c972e7faf1469b1710a353f1a098460b11274689f5f61d9504262a450f876719037423a68e87c0b

staging:
  secret_key_base: 5b52f06fda334bc1c0a0b2f494fad1d034ce6f89dbfccac7496d11fbf2f6233ab7284c099d9e10a3560ced35156f7e2679f04d2d97be0c84b301d084c1418cb4


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
